service: service_name
configValidationMode: 'off'

provider:
  env:
    test: test
  name: scaleway
  runtime: python310

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

functions:
  first:
    env:
      local: local
    handler: handler.handle



