# This workflow will install Python dependencies and deploy to scaleway's serverless functions.

name: Deploy to scaleway's serverless functions

on: 
  push:
    - tags:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Deploy to scaleway's serverless functions
      run: | 
        scw-serverless deploy app.py
      env:
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}