name: Set up poetry
description: Install poetry and python dependencies
runs:
  using: "composite"
  steps:
    - name: Install bash
      shell: sh
      run: |
        apk update
        apk add bash

    - uses: snok/install-poetry@v1
      with:
        version: 1.3.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache poetry dependencies
      id: cache-poetry-deps
      uses: actions/cache@v3
      with:
        path: .venv
        key: pydeps-${{ hashFiles('**/poetry.lock') }}

    - name: Install poetry dependencies
      shell: bash
      run: poetry install --no-interaction --no-root --with=dev
      if: steps.cache-deps.outputs.cache-hit != 'true'

    - name: Install scw_serverless
      shell: bash
      run: poetry install --no-interaction
